FROM apache/airflow:2.9.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    boto3==1.34.110 \
    awswrangler==3.8.0 \
    great-expectations==0.18.15 \
    pandas==2.2.2 \
    pyarrow==16.0.0 \
    python-dotenv==1.0.1
