name: CI

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install ruff
        run: pip install ruff==0.4.4

      - name: Run linter
        run: ruff check producer/ consumer/ dags/ scripts/ tests/

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install pydantic==2.7.1 faker==24.11.0 pytest==8.2.0

      - name: Run tests
        run: pytest tests/ -v --tb=short

  validate-compose:
    name: Validate docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check docker-compose config
        run: docker compose config --quiet
